export const ADD_BLACK_CARD = 'ADD_BLACK_CARD':
export const REMOVE_BLACK_CARD = 'REMOVE_BLACK_CARD';
export const ADD_WHITE_CARD = 'ADD_WHITE_CARD';
export const REMOVE_WHITE_CARD = 'REMOVE_WHITE_CARD';
